name: PiggyAntiCheats
main: PiggyAntiCheats\Main
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
author: MCPEPIG
permissions:
  piggyanticheats:
    default: op
    description: "Allow using all PiggyAntiCheats features"
    children:
      piggyanticheats.notify:
        default: op
        description: "Get notifications from suspicion checks"
